# Generated by Django 5.2.15 on 2026-07-19 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_holidays',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date'), name='uniq_user_holiday')],
            },
        ),
    ]
