/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts/signup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_signup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["accounts_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["accounts_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/archive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_archive_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/catch-up/queue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_catch_up_queue_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/future-log/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_future_log_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/logs/monthly/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_logs_monthly_retrieve"];
        put?: never;
        post: operations["bujo_logs_monthly_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/logs/today/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_logs_today_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/logs/weekly/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_logs_weekly_retrieve"];
        put?: never;
        post: operations["bujo_logs_weekly_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/migration/queue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_migration_queue_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/monthly-review/queue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_monthly_review_queue_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/recurring-templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_recurring_templates_list"];
        put?: never;
        post: operations["bujo_recurring_templates_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/recurring-templates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["bujo_recurring_templates_partial_update"];
        trace?: never;
    };
    "/api/bujo/recurring-templates/{id}/place/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bujo_recurring_templates_place_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/task-density/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Densidade de tarefas por dia do mês (Story 11.3, AC2) — apenas leitura
         *     agregada, informativa. Conta APENAS tarefas raiz (`parent_task__isnull=True`,
         *     mesma convenção de WeeklyLogView/LogSerializer/FutureLogView) somando as três
         *     fontes de "tarefa num dia D":
         *
         *     - daily  → dia = `log.log_date`;
         *     - weekly → dia = `scheduled_date` (NULL não conta — sem dia);
         *     - monthly/annual → dia = `scheduled_date` (idem).
         *
         *     As três fontes são disjuntas por tarefa (CHECK `task_exactly_one_log`), mas
         *     uma mesma data pode receber contagens de fontes diferentes — por isso as
         *     contagens são somadas por data. `Task.objects` (tenant-scoped, fail-closed)
         *     garante o isolamento por `user_id`; NUNCA `all_objects` (AD-12).
         */
        get: operations["bujo_task_density_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bujo_tasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/tasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["bujo_tasks_destroy"];
        options?: never;
        head?: never;
        patch: operations["bujo_tasks_partial_update"];
        trace?: never;
    };
    "/api/bujo/tasks/{id}/migrate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bujo_tasks_migrate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/tasks/{id}/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bujo_tasks_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/tasks/{id}/subtasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bujo_tasks_subtasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/tasks/{id}/transition/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bujo_tasks_transition_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bujo/weekly-review/queue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bujo_weekly_review_queue_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArchiveEntry: {
            type: components["schemas"]["TypeEnum"];
            /** Format: date */
            weekStart?: string | null;
            /** Format: date */
            monthFirst?: string | null;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        CatchUpQueue: {
            monthlyTasks: components["schemas"]["Task"][];
            weeklyTasks: components["schemas"]["Task"][];
            dailyTasks: components["schemas"]["Task"][];
        };
        /**
         * @description * `teal` - Teal
         *     * `purple` - Purple
         *     * `pink` - Pink
         *     * `yellow` - Yellow
         *     * `green` - Green
         *     * `blue` - Blue
         * @enum {string}
         */
        CategoryEnum: "teal" | "purple" | "pink" | "yellow" | "green" | "blue";
        /**
         * @description * `today` - today
         *     * `week` - week
         *     * `month` - month
         *     * `future` - future
         *     * `cancel` - cancel
         * @enum {string}
         */
        DestinationEnum: "today" | "week" | "month" | "future" | "cancel";
        /**
         * @description * `ui` - Urgent Important
         *     * `u` - Urgent
         *     * `i` - Important
         *     * `none` - None
         * @enum {string}
         */
        EisenhowerEnum: "ui" | "u" | "i" | "none";
        FutureLogMonthGroup: {
            year: number;
            month: number;
            tasks: components["schemas"]["Task"][];
        };
        Log: {
            /** Format: uuid */
            readonly id: string;
            /** Format: date */
            logDate: string;
            readonly tasks: components["schemas"]["Task"][];
        };
        MigrationQueue: {
            /** Format: date */
            logDate: string;
            tasks: components["schemas"]["Task"][];
        };
        MonthlyLog: {
            /** Format: date */
            monthFirst: string;
            tasks: components["schemas"]["Task"][];
            closed: boolean;
        };
        MonthlyReviewQueue: {
            /** Format: date */
            monthFirst: string;
            tasks: components["schemas"]["Task"][];
        };
        MonthlyTaskCreate: {
            /** Format: date */
            monthFirst: string;
            title: string;
            /** Format: date */
            scheduledDate?: string | null;
            description?: string | null;
            eisenhower?: (components["schemas"]["EisenhowerEnum"] | components["schemas"]["NullEnum"]) | null;
            category?: (components["schemas"]["CategoryEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PatchedRecurringTaskTemplateUpdate: {
            title?: string;
            description?: string | null;
            eisenhower?: (components["schemas"]["EisenhowerEnum"] | components["schemas"]["NullEnum"]) | null;
            recurrenceGroup?: components["schemas"]["RecurrenceGroupEnum"];
            recurrenceText?: string;
            active?: boolean;
        };
        PatchedTaskUpdate: {
            title?: string;
            description?: string | null;
            eisenhower?: (components["schemas"]["EisenhowerEnum"] | components["schemas"]["NullEnum"]) | null;
            category?: (components["schemas"]["CategoryEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date */
            scheduledDate?: string | null;
        };
        /**
         * @description * `before` - before
         *     * `after` - after
         * @enum {string}
         */
        PositionEnum: "before" | "after";
        /**
         * @description * `weekly` - Weekly
         *     * `monthly` - Monthly
         *     * `annual` - Annual
         * @enum {string}
         */
        RecurrenceGroupEnum: "weekly" | "monthly" | "annual";
        RecurringTaskTemplate: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            description?: string | null;
            eisenhower?: (components["schemas"]["EisenhowerEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            recurrenceGroup: components["schemas"]["RecurrenceGroupEnum"];
            recurrenceText: string;
            active?: boolean;
        };
        RecurringTaskTemplateCreate: {
            title: string;
            description?: string | null;
            eisenhower?: (components["schemas"]["EisenhowerEnum"] | components["schemas"]["NullEnum"]) | null;
            recurrenceGroup: components["schemas"]["RecurrenceGroupEnum"];
            recurrenceText: string;
            /** @default true */
            active: boolean;
        };
        RecurringTaskTemplatePlace: {
            /** Format: date */
            weekStart?: string;
            /** Format: date */
            monthFirst?: string;
            /** Format: date */
            scheduledDate?: string | null;
        };
        /**
         * @description * `pending` - Pending
         *     * `started` - Started
         *     * `completed` - Completed
         *     * `cancelled` - Cancelled
         *     * `migrated` - Migrated
         *     * `postponed` - Postponed
         * @enum {string}
         */
        StatusEnum: "pending" | "started" | "completed" | "cancelled" | "migrated" | "postponed";
        Task: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            description?: string | null;
            status?: components["schemas"]["StatusEnum"];
            eisenhower?: (components["schemas"]["EisenhowerEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            category?: (components["schemas"]["CategoryEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date */
            scheduledDate?: string | null;
            readonly subtasks: components["schemas"]["Task"][];
            migrationCount?: number;
            /** Format: uuid */
            migratedToTask?: string | null;
            /** Format: uuid */
            sourceTemplate?: string | null;
        };
        TaskCreate: {
            title: string;
            description?: string | null;
            eisenhower?: (components["schemas"]["EisenhowerEnum"] | components["schemas"]["NullEnum"]) | null;
            category?: (components["schemas"]["CategoryEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        TaskDensityEntry: {
            /** Format: date */
            date: string;
            count: number;
        };
        TaskDensityResponse: {
            density: components["schemas"]["TaskDensityEntry"][];
        };
        TaskMigrate: {
            destination: components["schemas"]["DestinationEnum"];
            /** Format: date */
            monthFirst?: string;
            /** Format: date */
            scheduledDate?: string | null;
        };
        TaskReorder: {
            /** Format: uuid */
            targetTaskId: string;
            position: components["schemas"]["PositionEnum"];
        };
        TaskTransitionRequest: {
            toStatus: components["schemas"]["ToStatusEnum"];
        };
        /**
         * @description * `pending` - Pending
         *     * `started` - Started
         *     * `completed` - Completed
         *     * `cancelled` - Cancelled
         *     * `migrated` - Migrated
         *     * `postponed` - Postponed
         * @enum {string}
         */
        ToStatusEnum: "pending" | "started" | "completed" | "cancelled" | "migrated" | "postponed";
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /**
         * @description * `weekly` - weekly
         *     * `monthly` - monthly
         * @enum {string}
         */
        TypeEnum: "weekly" | "monthly";
        WeeklyDay: {
            /** Format: date */
            date: string;
            tasks: components["schemas"]["Task"][];
        };
        WeeklyLog: {
            /** Format: date */
            weekStart: string;
            days: components["schemas"]["WeeklyDay"][];
            unscheduled: components["schemas"]["Task"][];
            closed: boolean;
        };
        WeeklyReviewQueue: {
            /** Format: date */
            weekStart: string;
            tasks: components["schemas"]["Task"][];
        };
        WeeklyTaskCreate: {
            /** Format: date */
            weekStart: string;
            title: string;
            /** Format: date */
            scheduledDate?: string | null;
            description?: string | null;
            eisenhower?: (components["schemas"]["EisenhowerEnum"] | components["schemas"]["NullEnum"]) | null;
            category?: (components["schemas"]["CategoryEnum"] | components["schemas"]["NullEnum"]) | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_signup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    accounts_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    bujo_archive_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveEntry"][];
                };
            };
        };
    };
    bujo_catch_up_queue_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatchUpQueue"];
                };
            };
        };
    };
    bujo_future_log_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FutureLogMonthGroup"][];
                };
            };
        };
    };
    bujo_logs_monthly_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyLog"];
                };
            };
        };
    };
    bujo_logs_monthly_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlyTaskCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_logs_today_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Log"];
                };
            };
        };
    };
    bujo_logs_weekly_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyLog"];
                };
            };
        };
    };
    bujo_logs_weekly_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyTaskCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_migration_queue_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationQueue"];
                };
            };
        };
    };
    bujo_monthly_review_queue_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReviewQueue"];
                };
            };
        };
    };
    bujo_recurring_templates_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTaskTemplate"][];
                };
            };
        };
    };
    bujo_recurring_templates_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringTaskTemplateCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTaskTemplate"];
                };
            };
        };
    };
    bujo_recurring_templates_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRecurringTaskTemplateUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTaskTemplate"];
                };
            };
        };
    };
    bujo_recurring_templates_place_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RecurringTaskTemplatePlace"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_task_density_retrieve: {
        parameters: {
            query: {
                month_first: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDensityResponse"];
                };
            };
        };
    };
    bujo_tasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_tasks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bujo_tasks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTaskUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_tasks_migrate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskMigrate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_tasks_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskReorder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_tasks_subtasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_tasks_transition_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskTransitionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    bujo_weekly_review_queue_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReviewQueue"];
                };
            };
        };
    };
}
