# Generated by Django 5.2.15 on 2026-07-20 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doctors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'time_blocks',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSubstanceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('substance_name', models.CharField(max_length=200)),
                ('laboratory', models.CharField(blank=True, max_length=200, null=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_versions', to='medications.medication')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substance_versions', to='medications.doctor')),
            ],
            options={
                'db_table': 'medication_substance_versions',
                'ordering': ['medication', '-effective_from', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('medication', 'effective_from'), name='uniq_substance_version_per_day')],
            },
        ),
        migrations.CreateModel(
            name='MedicationScheduleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('dose', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_versions', to='medications.medication')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_versions', to='medications.timeblock')),
            ],
            options={
                'db_table': 'medication_schedule_versions',
                'ordering': ['medication', 'time_block', '-effective_from', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('medication', 'time_block', 'effective_from'), name='uniq_schedule_version_per_day')],
            },
        ),
    ]
