# Generated by Django 5.2.15 on 2026-07-20 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDayEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('dose_at_time', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('scheduled', 'Scheduled'), ('ad_hoc', 'Ad Hoc')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_entries', to='medications.medication')),
                ('time_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='day_entries', to='medications.timeblock')),
            ],
            options={
                'db_table': 'medication_day_entries',
                'ordering': ['date', 'time_block', 'medication'],
                'constraints': [models.CheckConstraint(condition=models.Q(('source__in', ['scheduled', 'ad_hoc'])), name='med_day_entry_source_valid'), models.UniqueConstraint(condition=models.Q(('source', 'scheduled')), fields=('medication', 'time_block', 'date'), name='uniq_med_day_entry_scheduled')],
            },
        ),
    ]
