from django.urls import path

from bujo.views import (
    ArchiveView,
    CatchUpQueueView,
    FutureLogView,
    MigrationQueueView,
    MonthlyCycleView,
    MonthlyDensityView,
    MonthlyFutureLogSourceView,
    MonthlyLogView,
    MonthlyPreviousMonthlySourceView,
    MonthlyRecurringSourceView,
    MonthlyReviewQueueView,
    RecurringTaskTemplateDetailView,
    RecurringTaskTemplateListView,
    RecurringTaskTemplatePlaceView,
    RitualDecisionCreateView,
    SubtaskCreateView,
    TaskCreateView,
    TaskDensityView,
    TaskDetailView,
    TaskMigrateView,
    TaskReorderView,
    TaskTransitionView,
    TodayLogView,
    WeeklyCycleView,
    WeeklyDensityView,
    WeeklyLogView,
    WeeklyMonthlyInWeekSourceView,
    WeeklyPendingDailiesSourceView,
    WeeklyPreviousWeeklySourceView,
    WeeklyRecurringSourceView,
    WeeklyReviewQueueView,
)

urlpatterns = [
    path("logs/today/", TodayLogView.as_view(), name="bujo-today-log"),
    path("logs/weekly/", WeeklyLogView.as_view(), name="bujo-weekly-log"),
    path("logs/monthly/", MonthlyLogView.as_view(), name="bujo-monthly-log"),
    # Ciclo operacional (Story 14.1, AC8) — um endpoint de ação por tipo.
    path("logs/weekly/cycle/", WeeklyCycleView.as_view(), name="bujo-weekly-cycle"),
    path("logs/monthly/cycle/", MonthlyCycleView.as_view(), name="bujo-monthly-cycle"),
    path("archive/", ArchiveView.as_view(), name="bujo-archive"),
    path("future-log/", FutureLogView.as_view(), name="bujo-future-log"),
    path("migration/queue/", MigrationQueueView.as_view(), name="bujo-migration-queue"),
    path("weekly-review/queue/", WeeklyReviewQueueView.as_view(), name="bujo-weekly-review-queue"),
    path(
        "monthly-review/queue/",
        MonthlyReviewQueueView.as_view(),
        name="bujo-monthly-review-queue",
    ),
    path("tasks/", TaskCreateView.as_view(), name="bujo-task-create"),
    path("tasks/<uuid:pk>/", TaskDetailView.as_view(), name="bujo-task-detail"),
    path("tasks/<uuid:pk>/subtasks/", SubtaskCreateView.as_view(), name="bujo-task-subtasks"),
    path("tasks/<uuid:pk>/transition/", TaskTransitionView.as_view(), name="bujo-task-transition"),
    path("tasks/<uuid:pk>/reorder/", TaskReorderView.as_view(), name="bujo-task-reorder"),
    path("tasks/<uuid:pk>/migrate/", TaskMigrateView.as_view(), name="bujo-task-migrate"),
    path("catch-up/queue/", CatchUpQueueView.as_view(), name="bujo-catch-up-queue"),
    path("task-density/", TaskDensityView.as_view(), name="bujo-task-density"),
    path(
        "recurring-templates/",
        RecurringTaskTemplateListView.as_view(),
        name="bujo-recurring-template-list",
    ),
    path(
        "recurring-templates/<uuid:pk>/",
        RecurringTaskTemplateDetailView.as_view(),
        name="bujo-recurring-template-detail",
    ),
    # Fontes dos rituais (Story 14.2, AC3/AC4) — UMA rota por fonte, sem
    # agregador: a independência de carga/falha é estrutural, não um try/except.
    path(
        "rituals/weekly/sources/monthly-in-week/",
        WeeklyMonthlyInWeekSourceView.as_view(),
        name="bujo-ritual-weekly-monthly-in-week",
    ),
    path(
        "rituals/weekly/sources/recurring/",
        WeeklyRecurringSourceView.as_view(),
        name="bujo-ritual-weekly-recurring",
    ),
    path(
        "rituals/weekly/sources/previous-weekly/",
        WeeklyPreviousWeeklySourceView.as_view(),
        name="bujo-ritual-weekly-previous-weekly",
    ),
    path(
        "rituals/weekly/sources/pending-dailies/",
        WeeklyPendingDailiesSourceView.as_view(),
        name="bujo-ritual-weekly-pending-dailies",
    ),
    path(
        "rituals/weekly/density/",
        WeeklyDensityView.as_view(),
        name="bujo-ritual-weekly-density",
    ),
    path(
        "rituals/monthly/sources/recurring/",
        MonthlyRecurringSourceView.as_view(),
        name="bujo-ritual-monthly-recurring",
    ),
    path(
        "rituals/monthly/sources/future-log/",
        MonthlyFutureLogSourceView.as_view(),
        name="bujo-ritual-monthly-future-log",
    ),
    path(
        "rituals/monthly/sources/previous-monthly/",
        MonthlyPreviousMonthlySourceView.as_view(),
        name="bujo-ritual-monthly-previous-monthly",
    ),
    path(
        "rituals/monthly/density/",
        MonthlyDensityView.as_view(),
        name="bujo-ritual-monthly-density",
    ),
    path(
        "ritual-decisions/",
        RitualDecisionCreateView.as_view(),
        name="bujo-ritual-decision-create",
    ),
    path(
        "recurring-templates/<uuid:pk>/place/",
        RecurringTaskTemplatePlaceView.as_view(),
        name="bujo-recurring-template-place",
    ),
]
