# Generated by Django 5.2.15 on 2026-07-03 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('log_date', models.DateField()),
            ],
            options={
                'db_table': 'logs',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'log_date'), name='uniq_log_user_id_log_date')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('migrated', 'Migrated'), ('postponed', 'Postponed')], default='pending', max_length=16)),
                ('eisenhower', models.CharField(blank=True, choices=[('ui', 'Urgent Important'), ('u', 'Urgent'), ('i', 'Important'), ('none', 'None')], max_length=8, null=True)),
                ('order_index', models.FloatField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('migration_count', models.PositiveIntegerField(default=0)),
                ('source_template_id', models.UUIDField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bujo.log')),
                ('migrated_to_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_from', to='bujo.task')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='bujo.task')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['order_index'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'started', 'completed', 'cancelled', 'migrated', 'postponed'])), name='task_status_valid')],
            },
        ),
    ]
