# Generated by Django 5.2.15 on 2026-07-12 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo', '0002_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bujo.log'),
        ),
        migrations.CreateModel(
            name='MonthlyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('month_first', models.DateField()),
                ('body', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'monthly_log',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'month_first'), name='uniq_monthly_log_user_id_month_first'), models.CheckConstraint(condition=models.Q(('month_first__day', 1)), name='month_first_is_day_one')],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='monthly_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bujo.monthlylog'),
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('week_start', models.DateField()),
                ('body', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'weekly_log',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'week_start'), name='uniq_weekly_log_user_id_week_start'), models.CheckConstraint(condition=models.Q(('week_start__iso_week_day', 1)), name='week_start_is_monday')],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='weekly_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bujo.weeklylog'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('log__isnull', False), ('monthly_log__isnull', True), ('weekly_log__isnull', True)), models.Q(('log__isnull', True), ('monthly_log__isnull', True), ('weekly_log__isnull', False)), models.Q(('log__isnull', True), ('monthly_log__isnull', False), ('weekly_log__isnull', True)), _connector='OR'), name='task_exactly_one_log'),
        ),
    ]
