# Generated by Django 5.2.15 on 2026-07-14 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo', '0003_weekly_monthly_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('eisenhower', models.CharField(blank=True, choices=[('ui', 'Urgent Important'), ('u', 'Urgent'), ('i', 'Important'), ('none', 'None')], max_length=8, null=True)),
                ('recurrence_group', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=8)),
                ('recurrence_text', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recurring_task_templates',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='source_template_id',
        ),
        migrations.AddField(
            model_name='task',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='bujo.recurringtasktemplate'),
        ),
    ]
