# Generated by Django 5.2.15 on 2026-07-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo', '0004_recurringtasktemplate_remove_task_source_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtasktemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('teal', 'Teal'), ('purple', 'Purple'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue')], max_length=8, null=True),
        ),
    ]
