# Generated by Django 5.2.15 on 2026-07-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo', '0005_recurringtasktemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='waiting_on',
            field=models.BooleanField(default=False),
        ),
    ]
