# Generated by Django 5.2.15 on 2026-07-25 03:26
"""Estado do ciclo operacional em ``weekly_log``/``monthly_log`` + backfill (AD-28, Story 14.1).

Ordem das operations (deliberada): ``AddField`` ×4 → ``AddConstraint`` ×6 →
``RunPython`` do backfill. As uniques parciais entram **antes** do backfill para
que ele não possa, nem por bug, produzir dois ``active`` (ou dois ``planning``)
para o mesmo usuário — o invariante do AC7 é imposto pelo banco durante a
própria migração, não apenas conferido depois.

Notas de conformidade (§6.7, §6.9):

- ``apps.get_model`` devolve models **históricos**: sem ``TenantManager``
  (``use_in_migrations`` não está setado em ``core.tenant.TenantManager``) e sem
  o ``save()`` de ``TenantModel``. Consequência prática: as queries aqui são
  naturalmente NÃO-escopadas por tenant, então o backfill itera por usuário
  explicitamente e todo ``create()`` passa ``user_id=`` à mão. É por isso que
  este módulo **não** usa ``tenant_context`` — a exceção justificada de §6.7.
- ``core.calendar.today_for`` é importado direto. O guardrail de AST
  (``core/tests/test_guardrails.py``) ignora ``migrations/``, e a AD-04 quer uma
  única autoridade de "hoje": reimplementar o fuso do usuário aqui criaria uma
  segunda definição de "hoje" divergente. Tradeoff aceito: a migration fica
  acoplada a uma função de ``core`` que, se mudar de assinatura, quebra a
  reexecução histórica — risco baixo e preferível a duplicar a regra.
"""

from datetime import date

from django.db import migrations, models

from core.calendar import today_for, week_start_of

# Literais de status de tarefa CONGELADOS pelo agregado `Task` (Story 3.1) e
# repetidos aqui de propósito: uma migration não pode importar `bujo.models`
# (o enum pode evoluir e mudaria o significado histórico deste backfill).
UNDISPOSED = ("pending", "started")

BUCKETS = ("finalized", "active", "active_materializado", "null")


def current_key(*, kind: str, today: date) -> date:
    """Chave do período corrente para ``today``: segunda da semana / dia 1 do mês."""
    return week_start_of(today) if kind == "weekly" else today.replace(day=1)


def classify_cycle_status(*, kind: str, key: date, today: date, derived_closed: bool) -> str | None:
    """Bucket retroativo de UM ciclo existente (função **pura** — ponto de teste).

    ``kind``: ``"weekly"`` | ``"monthly"``. ``key``: ``week_start`` / ``month_first``.
    ``derived_closed``: resultado da derivação de fechamento vigente (Épico 4).

    Precedência (AC7 / AD-28 item 4) — a ORDEM é normativa:

    1. período **corrente** → ``"active"``. Vence ``finalized`` de propósito: é o
       que garante o invariante "exatamente um ``active`` por usuário por tabela" e
       o que faz o gate "Iniciar exige anterior finalizado" funcionar no primeiro
       uso real.
    2. período **futuro** → ``None``, INDEPENDENTE de ``derived_closed``. Um mês
       futuro é armazenamento do Future Log: ele nunca esteve no regime
       operacional, então não pode sair da migration como ``finalized`` só porque
       suas tarefas já estão dispostas. Esta linha vem antes da derivação de
       propósito — invertê-la finalizaria ciclos que nunca rodaram.
    3. passado **fechado pela derivação** → ``"finalized"``.
    4. resto (passado não-fechado) → ``None``: fora do regime operacional. Suas
       tarefas abertas são exatamente a população da fila unificada da Story 14.3.
    """
    current = current_key(kind=kind, today=today)
    if key == current:
        return "active"
    if key > current:
        return None
    if derived_closed:
        return "finalized"
    return None


def _derived_closed_map(Task, *, user_id, fk_name, log_ids):
    """``{log_id: bool}`` com a derivação de fechamento reimplementada localmente.

    Fechado = tem ≥1 tarefa **e** nenhuma da subárvore completa em
    ``pending``/``started``. Não filtra ``parent_task`` (subárvore inteira), igual
    a ``bujo.services.archive.is_container_closed`` — reimplementado em vez de
    importado porque migrations não podem depender de ``services``.
    """
    if not log_ids:
        return {}
    rows = (
        Task.objects.filter(user_id=user_id, **{f"{fk_name}__in": log_ids})
        .values(fk_name)
        .annotate(
            total=models.Count("id"),
            undisposed=models.Count("id", filter=models.Q(status__in=UNDISPOSED)),
        )
    )
    counts = {row[fk_name]: (row["total"], row["undisposed"]) for row in rows}
    return {
        log_id: (counts.get(log_id, (0, 0))[0] > 0 and counts.get(log_id, (0, 0))[1] == 0)
        for log_id in log_ids
    }


def _backfill_one(Model, Task, *, user, kind, key_field, fk_name, counts):
    """Aplica os buckets a todos os ciclos de UM usuário numa das duas tabelas."""
    today = today_for(user)
    logs = list(Model.objects.filter(user_id=user.id))
    closed = _derived_closed_map(
        Task, user_id=user.id, fk_name=fk_name, log_ids=[log.id for log in logs]
    )

    for log in logs:
        new_status = classify_cycle_status(
            kind=kind,
            key=getattr(log, key_field),
            today=today,
            derived_closed=closed.get(log.id, False),
        )
        if log.status != new_status:
            log.status = new_status
            log.save(update_fields=["status"])
        counts[new_status or "null"] += 1

    # AC7: o ciclo do período corrente é `active` mesmo quando ainda não existe —
    # materializado DENTRO da migration para que todo usuário varrido tenha
    # exatamente um `active` por tabela (zero ciclos órfãos).
    key = current_key(kind=kind, today=today)
    if not any(getattr(log, key_field) == key for log in logs):
        # `user_id` explícito: o model histórico não carrega o `save()` de
        # `TenantModel` que faria o auto-fill a partir do contexto de tenant.
        Model.objects.create(user_id=user.id, status="active", **{key_field: key})
        counts["active"] += 1
        counts["active_materializado"] += 1


def backfill(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    WeeklyLog = apps.get_model("bujo", "WeeklyLog")
    MonthlyLog = apps.get_model("bujo", "MonthlyLog")
    Task = apps.get_model("bujo", "Task")

    # Varre SÓ quem já usou o BuJo (AC7): materializar ciclo para conta que nunca
    # usou contradiz a política de materialização sob demanda que a AC4 protege e
    # inflaria as contagens. União dos `user_id` presentes nas três tabelas.
    user_ids = set()
    for model in (WeeklyLog, MonthlyLog, Task):
        user_ids.update(model.objects.values_list("user_id", flat=True).distinct())

    if not user_ids:
        # Banco vazio — inclusive o banco de teste, que nasce das migrations em toda
        # sessão de pytest. Sai numa linha para não poluir a saída dos testes.
        print("\n[0007 backfill] nenhum usuário com dados de BuJo — nada a fazer")
        return

    counts = {
        "weekly_log": dict.fromkeys(BUCKETS, 0),
        "monthly_log": dict.fromkeys(BUCKETS, 0),
    }
    users = User.objects.filter(id__in=user_ids)

    for user in users:
        _backfill_one(
            WeeklyLog,
            Task,
            user=user,
            kind="weekly",
            key_field="week_start",
            fk_name="weekly_log_id",
            counts=counts["weekly_log"],
        )
        _backfill_one(
            MonthlyLog,
            Task,
            user=user,
            kind="monthly",
            key_field="month_first",
            fk_name="monthly_log_id",
            counts=counts["monthly_log"],
        )

    # Contagens por tabela × bucket: a evidência contratada pelo AC7 (o backfill
    # sobre dados reais não é testável pelo pytest — o banco de teste nasce vazio
    # das migrations, então esta saída do `migrate` é a prova).
    print(f"\n[0007 backfill] usuários varridos: {users.count()} (de {len(user_ids)} ids)")
    for table, table_counts in counts.items():
        detail = ", ".join(f"{bucket}={table_counts[bucket]}" for bucket in BUCKETS)
        print(f"[0007 backfill] {table}: {detail}")


class Migration(migrations.Migration):

    dependencies = [
        ('bujo', '0006_task_waiting_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlylog',
            name='planning_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='monthlylog',
            name='status',
            field=models.CharField(blank=True, choices=[('planning', 'Planning'), ('active', 'Active'), ('finalized', 'Finalized')], default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='planning_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(blank=True, choices=[('planning', 'Planning'), ('active', 'Active'), ('finalized', 'Finalized')], default=None, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='monthlylog',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planning', 'active', 'finalized']), ('status__isnull', True), _connector='OR'), name='monthly_log_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='monthlylog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user_id',), name='uniq_monthly_log_active_per_user'),
        ),
        migrations.AddConstraint(
            model_name='monthlylog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'planning')), fields=('user_id',), name='uniq_monthly_log_planning_per_user'),
        ),
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planning', 'active', 'finalized']), ('status__isnull', True), _connector='OR'), name='weekly_log_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user_id',), name='uniq_weekly_log_active_per_user'),
        ),
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'planning')), fields=('user_id',), name='uniq_weekly_log_planning_per_user'),
        ),
        # noop na reversão: reverter esta migration DERRUBA as colunas `status` e
        # `planning_completed_at` (os `RemoveField` reversos), então não há dado a
        # restaurar — não existe estado anterior para o qual voltar.
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
