# Generated by Django 5.2.15 on 2026-07-25 05:43
#
# Story 14.2 — `ritual_decisions` (AD-28 item 6). Schema PURO, sem `RunPython`:
# não existe dado retroativo a backfillar porque decisões-snapshot nascem com o
# ritual, e nenhum ritual rodou antes desta tabela existir. (Contraste com a
# 0007, que precisou da primeira `RunPython` do repo para classificar ciclos
# preexistentes.)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo', '0007_weekly_monthly_cycle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RitualDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('decision', models.CharField(choices=[('keep', 'Keep'), ('skip_week', 'Skip Week'), ('keep_undated', 'Keep Undated')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ritual_decisions', to='bujo.monthlylog')),
                ('recurring_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ritual_decisions', to='bujo.recurringtasktemplate')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ritual_decisions', to='bujo.task')),
                ('weekly_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ritual_decisions', to='bujo.weeklylog')),
            ],
            options={
                'db_table': 'ritual_decisions',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('monthly_log__isnull', True), ('weekly_log__isnull', False)), models.Q(('monthly_log__isnull', False), ('weekly_log__isnull', True)), _connector='OR'), name='ritual_decision_exactly_one_target'), models.CheckConstraint(condition=models.Q(models.Q(('recurring_template__isnull', True), ('task__isnull', False)), models.Q(('recurring_template__isnull', False), ('task__isnull', True)), _connector='OR'), name='ritual_decision_exactly_one_item'), models.CheckConstraint(condition=models.Q(('decision__in', ['keep', 'skip_week', 'keep_undated'])), name='ritual_decision_valid'), models.UniqueConstraint(condition=models.Q(('task__isnull', False), ('weekly_log__isnull', False)), fields=('weekly_log', 'task'), name='uniq_ritual_decision_weekly_task'), models.UniqueConstraint(condition=models.Q(('recurring_template__isnull', False), ('weekly_log__isnull', False)), fields=('weekly_log', 'recurring_template'), name='uniq_ritual_decision_weekly_recurring'), models.UniqueConstraint(condition=models.Q(('monthly_log__isnull', False), ('task__isnull', False)), fields=('monthly_log', 'task'), name='uniq_ritual_decision_monthly_task'), models.UniqueConstraint(condition=models.Q(('monthly_log__isnull', False), ('recurring_template__isnull', False)), fields=('monthly_log', 'recurring_template'), name='uniq_ritual_decision_monthly_recurring')],
            },
        ),
    ]
