# Generated by Django 5.2.15 on 2026-07-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujo', '0008_ritual_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtasktemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
