# Generated by Django 5.2.15 on 2026-07-16 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainDumpItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_log', models.CharField(blank=True, choices=[('today', 'Today'), ('week', 'Week'), ('month', 'Month'), ('future', 'Future')], max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brain_dump_items',
                'ordering': ['created_at'],
            },
        ),
    ]
