# Generated by Django 5.2.15 on 2026-07-17 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'habit_groups',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('emoticon', models.CharField(blank=True, max_length=16)),
                ('type', models.CharField(choices=[('boolean', 'Boolean'), ('numeric', 'Numeric')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habits', to='habits.habitgroup')),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HabitVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='habits.habit')),
            ],
            options={
                'db_table': 'habit_versions',
                'ordering': ['habit', '-effective_from', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['boolean', 'numeric'])), name='habit_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='habitversion',
            constraint=models.UniqueConstraint(fields=('habit', 'effective_from'), name='uniq_habit_version_per_day'),
        ),
    ]
