# Generated by Django 5.2.15 on 2026-07-18 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='HabitDayEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_at_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meta_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_entries', to='habits.habit')),
            ],
            options={
                'db_table': 'habit_day_entries',
                'ordering': ['date', 'habit'],
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='uniq_habit_day_entry_per_day')],
            },
        ),
    ]
