# Generated by Django 5.2.15 on 2026-07-19 13:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_day_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitdayentry',
            name='day_type',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend'), ('holiday', 'Holiday')], default='weekday', max_length=8),
        ),
        migrations.AddField(
            model_name='habitdayentry',
            name='multiplier_at_time',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
        migrations.CreateModel(
            name='HabitGroupDayMultiplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('day_type', models.CharField(choices=[('weekend', 'Weekend'), ('holiday', 'Holiday')], max_length=8)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_multipliers', to='habits.habitgroup')),
            ],
            options={
                'db_table': 'habit_group_day_multipliers',
                'ordering': ['group', 'day_type', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('group', 'day_type', 'effective_from'), name='uniq_group_day_multiplier_per_day'), models.CheckConstraint(condition=models.Q(('day_type__in', ['weekend', 'holiday'])), name='group_multiplier_day_type_valid')],
            },
        ),
    ]
