# Generated by Django 5.2.15 on 2026-08-23 01:05
"""``Habit.icon_key`` + conversão dos ``emoticon`` existentes (Story 16.2).

O gate 16.0 decidiu que **o emoji sai da interface de Hábitos**, sem fallback:
todo pictograma passa a ser um nome de glifo Phosphor (``icon_key``, kebab-case).
A conversão de cada ``emoticon`` já gravado é passo de **migração de dado desta
story**, não escolha adiada para o usuário (EXPERIENCE.md §Pictogramas de hábitos
e saúde).

Ordem das operations: ``AddField`` → ``RunPython`` do backfill.

Notas de conformidade (§6.7, §6.9), no molde de ``bujo/0007``:

- O mapa ``EMOJI_TO_ICON_KEY`` é **literal congelado**. Uma migration não pode
  importar ``core.phosphor`` nem ``habits.models``: o catálogo do Phosphor muda a
  cada upgrade do pacote e os models evoluem, e qualquer um dos dois mudaria o
  significado histórico deste backfill. O preço é que as chaves aqui não são
  revalidadas contra o catálogo vivo — aceito de propósito: foram conferidas
  contra ``@phosphor-icons/react@2.1.10`` no momento de escrever, e um glifo
  que saia do pacote depois degrada para coluna vazia na UI (a regra de ausência
  do gate 16.0), nunca para tofu.
- ``apps.get_model`` devolve models **históricos**: sem ``TenantManager``
  (``use_in_migrations`` não está setado em ``core.tenant.TenantManager``). As
  queries aqui são portanto NÃO-escopadas por tenant — o backfill varre a tabela
  inteira de propósito e nunca usa ``tenant_context`` (exceção justificada de
  §6.7). Como não há ``create()``, não há ``user_id`` a preencher à mão; o
  ``update`` preserva o ``user_id`` de cada linha.
- ``emoticon`` **não** é lido para trás nem apagado: permanece como dado
  histórico até a onda de remoção do legado, e as superfícies legado ainda o
  leem. Este backfill só ESCREVE ``icon_key``.
- A migration **nunca falha** por emoji desconhecido — emoji fora do mapa
  simplesmente deixa ``icon_key`` em ``NULL`` (hábito sem pictograma é estado
  válido; a coluna do glifo fica vazia).
"""

from django.db import migrations, models

# Mapa emoji → nome de glifo Phosphor (kebab-case), CONGELADO nesta migration.
# A superfície legado de Hábitos oferece um campo de texto livre para o emoji
# (``HabitsManager.tsx``), então a população real é aberta: o mapa cobre o
# vocabulário praticável de rastreio de hábitos e tudo que ficar de fora cai em
# NULL, por desenho. Todas as chaves foram conferidas contra
# @phosphor-icons/react@2.1.10.
EMOJI_TO_ICON_KEY = {
    # Marcação / conclusão
    "✅": "check-circle",
    "☑️": "check-square",
    "✔️": "check",
    "✔": "check",
    "🎯": "target",
    "⭐": "star",
    "⭐️": "star",
    "🌟": "star",
    "🏆": "trophy",
    "🥇": "medal",
    "🔥": "fire",
    "⚡": "lightning",
    "⚡️": "lightning",
    # Corpo e exercício
    "🏋️": "barbell",
    "🏋️‍♂️": "barbell",
    "🏋️‍♀️": "barbell",
    "🏃": "person-simple-run",
    "🏃‍♂️": "person-simple-run",
    "🏃‍♀️": "person-simple-run",
    "🚶": "person-simple-walk",
    "🚴": "person-simple-bike",
    "🚲": "bicycle",
    "🏊": "person-simple-swim",
    "🧘": "person-simple-tai-chi",
    "🧘‍♂️": "person-simple-tai-chi",
    "🧘‍♀️": "person-simple-tai-chi",
    "🤸": "person-simple-tai-chi",
    "⚽": "soccer-ball",
    "🏀": "basketball",
    "🎾": "tennis-ball",
    "🏐": "volleyball",
    "🥊": "boxing-glove",
    "👟": "sneaker",
    "👣": "footprints",
    # Saúde e cuidado
    "💊": "pill",
    "💉": "syringe",
    "🩺": "stethoscope",
    "🌡️": "thermometer",
    "🩹": "bandaids",
    "🏥": "first-aid-kit",
    "❤️": "heart",
    "♥️": "heart",
    "💓": "heartbeat",
    "💗": "heartbeat",
    "🫀": "heartbeat",
    "🦷": "tooth",
    "🚿": "shower",
    "🛁": "bathtub",
    "🧼": "hand-soap",
    "⚖️": "scales",
    # Sono e ritmo do dia
    "😴": "bed",
    "🛏️": "bed",
    "🌙": "moon",
    "🌜": "moon",
    "🌛": "moon",
    "☀️": "sun",
    "🌞": "sun",
    "🌅": "sun-horizon",
    "⏰": "alarm",
    "⏱️": "timer",
    "⏳": "hourglass",
    "🕐": "clock",
    "📅": "calendar",
    # Comida e bebida
    "💧": "drop",
    "🚰": "drop",
    "🥤": "drop-simple",
    "☕": "coffee",
    "🍵": "tea-bag",
    "🥕": "carrot",
    "🍎": "apple-logo",
    "🍏": "apple-logo",
    "🍽️": "fork-knife",
    "🥗": "bowl-food",
    "🍳": "egg",
    "🥚": "egg",
    "🐟": "fish",
    "🧀": "cheese",
    "🍞": "bread",
    "🍪": "cookie",
    "🍕": "pizza",
    "🍔": "hamburger",
    "🍦": "ice-cream",
    "🍿": "popcorn",
    "🍺": "beer-bottle",
    "🍷": "wine",
    "🍸": "martini",
    "🍾": "champagne",
    "🚬": "cigarette",
    "🚫": "prohibit",
    # Mente, estudo e criação
    "🧠": "brain",
    "📖": "book-open",
    "📚": "book",
    "📕": "book",
    "✍️": "pencil",
    "📝": "note-pencil",
    "📓": "notebook",
    "📔": "notebook",
    "📰": "newspaper",
    "🎓": "graduation-cap",
    "🗣️": "translate",
    "🎨": "paint-brush",
    "🖌️": "paint-brush",
    "🎸": "guitar",
    "🎵": "music-note",
    "🎶": "music-notes",
    "🎤": "microphone",
    "🎧": "headphones",
    "🙏": "hands-praying",
    "☯️": "yin-yang",
    "💡": "lightbulb",
    # Trabalho e finanças
    "💻": "laptop",
    "👨‍💻": "code",
    "👩‍💻": "code",
    "💼": "briefcase",
    "💰": "money",
    "💵": "money",
    "🐷": "piggy-bank",
    "🏦": "bank",
    "💳": "credit-card",
    "🧾": "receipt",
    "📊": "chart-bar",
    "📈": "chart-line",
    "🗒️": "clipboard-text",
    "✉️": "envelope",
    "📞": "phone",
    "📱": "device-mobile",
    # Casa, natureza e outros
    "🏠": "house",
    "🧹": "broom",
    "🗑️": "trash",
    "♻️": "recycle",
    "🛒": "shopping-cart",
    "🌱": "plant",
    "🪴": "potted-plant",
    "🌳": "tree",
    "🍃": "leaf",
    "🌸": "flower",
    "🌻": "flower",
    "⛰️": "mountains",
    "🐶": "dog",
    "🐕": "dog",
    "🐱": "cat",
    "🐈": "cat",
    "🚗": "car",
    "✈️": "airplane",
    "🎁": "gift",
    "🎉": "confetti",
    "🎂": "cake",
    "📷": "camera",
    "📺": "television",
    "🎮": "game-controller",
    "🚀": "rocket",
    "🙂": "smiley",
    "😊": "smiley",
    "👤": "user",
    "👥": "users",
}


def icon_key_for_emoticon(emoticon):
    """Nome de glifo para um ``emoticon``, ou ``None`` (função **pura** — ponto de teste).

    Regra de ausência, nunca de substituto: emoji vazio, em branco, ou fora do
    mapa congelado devolve ``None`` — o hábito simplesmente fica sem pictograma
    e a coluna do glifo aparece vazia. O emoji NUNCA é usado como fallback de
    renderização (decisão do gate 16.0).

    A busca é tolerante ao seletor de variação Unicode ``U+FE0F``: a mesma
    aparência pode ter sido digitada com ou sem ele (``❤️`` × ``❤``), e as duas
    grafias devem convergir para a mesma chave.

    Também degrada para o **emoji base** quando a grafia carrega enfeites que o
    pictograma monocromático não representa de todo modo:

    - **modificador de tom de pele** (``U+1F3FB``–``U+1F3FF``): ``🏃🏽`` é o mesmo
      glifo que ``🏃`` — o Phosphor não tem variante de tom;
    - **sequência ZWJ de gênero** (``U+200D`` + ``♀``/``♂``): ``🚶‍♀️`` cai para
      ``🚶`` quando a variante com gênero não está no mapa.

    Sem essa degradação, um usuário que digitou o emoji com tom de pele perderia
    o pictograma na migração (``NULL``) embora o emoji base esteja mapeado — perda
    silenciosa, e não a "ausência por escolha" que o gate 16.0 desenhou.
    """
    if not emoticon:
        return None
    candidate = emoticon.strip()
    if not candidate:
        return None
    if candidate in EMOJI_TO_ICON_KEY:
        return EMOJI_TO_ICON_KEY[candidate]
    # Segunda tentativa sem o seletor de variação (e vice-versa).
    stripped = candidate.replace("️", "")
    if stripped in EMOJI_TO_ICON_KEY:
        return EMOJI_TO_ICON_KEY[stripped]
    with_vs = EMOJI_TO_ICON_KEY.get(f"{stripped}️")
    if with_vs is not None:
        return with_vs
    # Terceira tentativa: remove tom de pele e cauda de gênero ZWJ, e reconsulta o
    # emoji base pelas mesmas duas grafias. Literais congelados como o resto do
    # mapa — a migration não importa `re` nem tabelas Unicode vivas.
    base = "".join(c for c in stripped if not ("\U0001f3fb" <= c <= "\U0001f3ff"))
    zwj = base.find("‍")
    if zwj != -1:
        base = base[:zwj]
    if base and base != stripped:
        return EMOJI_TO_ICON_KEY.get(base) or EMOJI_TO_ICON_KEY.get(f"{base}️")
    return None


def backfill_icon_key(apps, schema_editor):
    """Converte ``emoticon`` → ``icon_key`` em todos os hábitos, sem tocar ``emoticon``."""
    Habit = apps.get_model("habits", "Habit")

    # Model histórico: `objects` NÃO é escopado por tenant (§6.7), então esta
    # varredura é global de propósito — a conversão vale para todos os usuários.
    # Só as linhas COM emoji entram: sem `emoticon`, `icon_key` já nasce NULL.
    # `only()` de propósito: a tabela pode ser grande e só estes dois campos
    # importam. `icon_key` fica deferido, mas é ATRIBUÍDO antes do save — o
    # `update_fields` grava o valor novo sem precisar tê-lo carregado.
    rows = list(Habit.objects.exclude(emoticon="").only("id", "emoticon"))
    if not rows:
        print("\n[habits 0004 backfill] nenhum hábito com emoticon — nada a fazer")
        return

    converted = 0
    unmapped = 0
    for habit in rows:
        icon_key = icon_key_for_emoticon(habit.emoticon)
        if icon_key is None:
            unmapped += 1
            continue
        habit.icon_key = icon_key
        habit.save(update_fields=["icon_key"])
        converted += 1

    # Evidência do AC de migração: o backfill sobre dados reais não é testável
    # pelo pytest (o banco de teste nasce vazio das migrations), então esta
    # saída do `migrate` é a prova. Mesmo padrão de `bujo/0007`.
    print(
        f"\n[habits 0004 backfill] hábitos com emoticon: {len(rows)} | "
        f"convertidos: {converted} | sem mapeamento (icon_key=NULL): {unmapped}"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_day_type_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='icon_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        # noop na reversão: reverter esta migration DERRUBA a coluna `icon_key`
        # (o `RemoveField` reverso do `AddField` acima), então não há dado a
        # restaurar — e `emoticon`, a única fonte, nunca foi tocado.
        migrations.RunPython(backfill_icon_key, migrations.RunPython.noop),
    ]
