# Generated by Django 5.2.15 on 2026-07-19 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('enum', 'Enum'), ('text', 'Text')], max_length=10)),
                ('enum_options', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_field_definitions',
                'ordering': ['display_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('field_type__in', ['integer', 'decimal', 'boolean', 'enum', 'text'])), name='health_field_type_valid')],
            },
        ),
    ]
