# Generated by Django 5.2.15 on 2026-07-19 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_logs',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date'), name='uniq_health_log_per_day')],
            },
        ),
    ]
