# Generated by Django 5.2.15 on 2026-08-23 01:05
"""``HealthFieldDefinition.icon_key`` (Story 16.2) — ``AddField`` puro.

Saúde não tem ``emoticon``: não há dado legado a converter, então esta migration
não carrega ``RunPython`` (o par em ``habits/0004_icon_key.py`` tem). O campo
entra agora, sem UI, porque a Story 16.4 está atrás do gate UX 16.3 e ter a
coluna já criada evita uma segunda migration lá.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_health_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfielddefinition',
            name='icon_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
